### ISSUE TITLE
2 Unknown SimpleITK classes

### ISSUE THREAD

**Issue by jamesobutler** [SimpleITK/SlicerSimpleFilters#11]
When using Slicer 4.10.0, opening the SimpleFilters module reveals the following errors in the python interactor:
```python
Unknown SimpleITK class "CoherenceEnhancingDiffusionImageFilter".
Unknown SimpleITK class "ObjectnessMeasureImageFilter".
```
This is also seen in the [log](http://slicer.cdash.org/testDetails.php?test=9269779&build=1421180) of a failed SimpleFiltersModuleTest on the chiasma.queens build site, so I don't believe it is specific to my system.

**Comment by blowekamp** [comment]
Thanks for the report. The error/warning can safely be ignored, but it should be fixed.

The message is coming from here: https://github.com/SimpleITK/SlicerSimpleFilters/blob/92cbe91774350aca201b01de91ec1fa265173789/SimpleFilters/SimpleFilters.py#L104

These filters come from ITK modules which on not enabled currently in the Slicer configuration. The correct thing to do is to check `sitk::Version::ITKModulesEnabled()` for the module in the json file that is specified. If the module is not there then simply don't produce an  error/warning.
